Fixed the linux/amd64 build using Zig compiler.

diff --git a/.github/workflows/linux_amd64_zig_build.yaml b/.github/workflows/linux_amd64_zig_build.yaml
--- a/.github/workflows/linux_amd64_zig_build.yaml
+++ b/.github/workflows/linux_amd64_zig_build.yaml
@@ -8,16 +8,16 @@ permissions:
 
 jobs:
   build-and-package-linux-amd64:
-    name: "Build PJRT (Zig Target glibc 2.34)"
+    name: "Build PJRT"
     runs-on: ubuntu-latest # Fastest runner, no queue issues
     env:
       GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
     steps:
-      - name: "Free disk space"
-        run: |
-          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
-          df -h
+      # - name: "Free disk space"
+      #   run: |
+      #     sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
+      #     df -h
 
       - uses: actions/checkout@v4
 
@@ -25,6 +25,55 @@ jobs:
         uses: mlugg/setup-zig@v2
         with:
           version: "latest" # Latest full release.
+
+      - name: "Setup Zip as C++ tools"
+        run: |
+          # 1. Setup Zig related env variables.
+          export TOOLCHAIN_PATH="$(pwd)/internal/zig-bin"
+          echo "TOOLCHAIN_PATH=$TOOLCHAIN_PATH" >> $GITHUB_ENV
+
+          export ZIG_CACHE="$(pwd)/.zig-cache"
+          export ZIG_LOCAL_CACHE_DIR="$ZIG_CACHE"
+          export ZIG_GLOBAL_CACHE_DIR="$ZIG_CACHE"
+          echo "ZIG_CACHE=$ZIG_CACHE" >> $GITHUB_ENV
+          echo "ZIG_LOCAL_CACHE_DIR=$ZIG_LOCAL_CACHE_DIR" >> $GITHUB_ENV
+          echo "ZIG_GLOBAL_CACHE_DIR=$ZIG_GLOBAL_CACHE_DIR" >> $GITHUB_ENV
+
+          ZIG_EXE=$(which zig)
+          echo "ZIG_EXE=$ZIG_EXE" >> $GITHUB_ENV
+
+          # Capture Zig's internal paths for Bazel
+          ZIG_LIB_DIR=$($ZIG_EXE env | grep '\.lib_dir =' | cut -d '"' -f 2)
+          echo "ZIG_LIB_DIR=$ZIG_LIB_DIR" >> $GITHUB_ENV
+          echo "TOOLCHAIN_PATH=$TOOLCHAIN_PATH" >> $GITHUB_ENV
+
+          # 3. Copy / symlink the required tools directly to zig
+          cp ${TOOLCHAIN_PATH}/compiler-wrapper.sh "${TOOLCHAIN_PATH}/clang"
+          cp ${TOOLCHAIN_PATH}/compiler-wrapper.sh "${TOOLCHAIN_PATH}/clang++"
+          chmod +x "${TOOLCHAIN_PATH}/clang" "${TOOLCHAIN_PATH}/clang++"
+          for tool in ld.lld llvm-ar llvm-nm llvm-objcopy llvm-objdump llvm-strip; do
+            ln -s "$ZIG_EXE" "${TOOLCHAIN_PATH}/$tool"
+          done
+
+      - name: "Verify Zig-C++ Toolchain"
+        run: |
+          echo "clang (zig-based) version: [$(echo "__clang_major__" | ${TOOLCHAIN_PATH}/clang -E -P -)]"
+          echo "Zig environment:"
+          zig env
+          echo "-----------------------------------"
+
+          # Create and compile a dummy C++ file
+          export CC="$TOOLCHAIN_PATH/clang"
+          export CXX="$TOOLCHAIN_PATH/clang++"
+          printf "#include <cstdint>\n#include <vector>\nint main() { std::vector<uint32_t> v; return 0; }\n" > test.cpp
+          echo "Testing C++ header availability..."
+          $CXX -c test.cpp -o test.o
+          if [ $? -eq 0 ]; then
+            echo "✅ Zig C++ headers found successfully!"
+          else
+            echo "❌ Zig C++ headers NOT found. Check wrapper logic."
+            exit 1
+          fi
 
       - name: "Clone and checkout XLA"
         run: |
@@ -49,28 +98,15 @@ jobs:
       - name: "Setup Bazelisk"
         uses: bazelbuild/setup-bazelisk@v3
 
-      - name: "Setup Zip as C++ tools"
+      - name: "Build Version"
         run: |
-          # 1. Setup Zig related env variables.
-          export TOOLCHAIN_PATH="$(pwd)/internal/zig-bin"
-          echo "TOOLCHAIN_PATH=$TOOLCHAIN_PATH" >> $GITHUB_ENV
-          chmod +x "${TOOLCHAIN_PATH}/clang" "${TOOLCHAIN_PATH}/clang++"
-
-          ZIG_CACHE="$(pwd)/.zig-cache"
-          mkdir -p "${ZIG_CACHE}"
-          echo "ZIG_CACHE=$ZIG_CACHE" >> $GITHUB_ENV
-
-          ZIG_EXE=$(which zig)
-          echo "ZIG_EXE=$ZIG_EXE" >> $GITHUB_ENV
-
-          # 3. Symlink other required tools directly to zig
-          # Zig handles these calls automatically based on the symlink name
-          ln -s $ZIG_EXE "${TOOLCHAIN_PATH}"/ld.lld
-          ln -s $ZIG_EXE "${TOOLCHAIN_PATH}"/llvm-ar
-          ln -s $ZIG_EXE "${TOOLCHAIN_PATH}"/llvm-nm
-          ln -s $ZIG_EXE "${TOOLCHAIN_PATH}"/llvm-objcopy
-          ln -s $ZIG_EXE "${TOOLCHAIN_PATH}"/llvm-objdump
-          ln -s $ZIG_EXE "${TOOLCHAIN_PATH}"/llvm-strip
+          # Extract version numbers
+          BUILDER_VERSION="$(cat BUILDER_VERSION.txt)"
+          PJRT_C_API_HEADER="./xla/xla/pjrt/c/pjrt_c_api.h"
+          MAJOR=$(grep -E '#define PJRT_API_MAJOR' "${PJRT_C_API_HEADER}" | awk '{print $3}')
+          MINOR=$(grep -E '#define PJRT_API_MINOR' "${PJRT_C_API_HEADER}" | awk '{print $3}')
+          echo "Building PJRT CPU plugin for version ${MAJOR}.${MINOR} (to be used in go-xla as v${MAJOR}.${MINOR}.${BUILDER_VERSION})"
+          echo "RELEASE_VERSION=v${MAJOR}.${MINOR}.${BUILDER_VERSION}" >> $GITHUB_ENV
 
       - name: "Build PJRT C API CPU plugin"
         run: |
@@ -86,18 +122,27 @@ jobs:
             --host_compiler CLANG \
             --clang_path "$CC"
 
-          # 5. Build
-          # We force Bazel to use our wrappers for everything
+          ZIG_INCLUDE_PATH="${ZIG_LIB_DIR}/libcxx/include:${ZIG_LIB_DIR}/libc/include"
+          echo "ZIG_INCLUDE_PATH=$ZIG_INCLUDE_PATH"
+          echo
+
           bazel build -c opt \
             --action_env=CC="$CC" \
-            --action_env=CXX="$CXX" \
-            --action_env=ZIG_EXE="$ZIG_EXE" \
-            --action_env=ZIG_CACHE="$ZIG_CACHE" \
             --host_action_env=CC="$CC" \
+            --action_env=CXX="$CXX" \
             --host_action_env=CXX="$CXX" \
+            --action_env=ZIG_EXE="$ZIG_EXE" \
+            --host_action_env=ZIG_EXE="$ZIG_EXE" \
+            --sandbox_writable_path="$ZIG_CACHE" \
+            --action_env=ZIG_CACHE="$ZIG_CACHE" \
+            --host_action_env=ZIG_CACHE="$ZIG_CACHE" \
+            --action_env=ZIG_LOCAL_CACHE_DIR="$ZIG_LOCAL_CACHE_DIR" \
+            --host_action_env=ZIG_LOCAL_CACHE_DIR="$ZIG_LOCAL_CACHE_DIR" \
+            --action_env=ZIG_GLOBAL_CACHE_DIR="$ZIG_GLOBAL_CACHE_DIR" \
+            --host_action_env=ZIG_GLOBAL_CACHE_DIR="$ZIG_GLOBAL_CACHE_DIR" \
+            --cxxopt="-stdlib=libc++" \
             --linkopt="-fuse-ld=lld" \
-            --local_ram_resources=HOST_RAM*.7 \
-            --local_cpu_resources=HOST_CPUS-1 \
+            --copt="-mavx512f" --copt="-mevex512" \
             //xla/pjrt/c:pjrt_c_api_cpu_plugin.so
 
       - name: "Verify glibc requirements"
